services:
  app:
    build: .
    container_name: crud-redes-app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql
      DB_NAME: crud_redes
      DB_USER: root
      DB_PASSWORD: ascent

  mysql:
    image: mysql:8.4
    container_name: crud-redes-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ascent
      MYSQL_DATABASE: crud_redes
      #MYSQL_USER: root
      #MYSQL_PASSWORD: ascent
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      # opcional: inicializaci√≥n con SQL
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  db_data:
